version: '3.8'

services:
  php:
    image: ghcr.io/steel0237-sprintf/test/php-web:${TAG:-latest}
    logging:
      options:
        max-size: "50m"
        max-file: "5"
    environment:
      TZ: "Europe/Moscow"
      ENV: ${ENV:-pro}
      APP_ENV: ${APP_ENV:-prod}
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname == worker1]

  nginx:
    image: ghcr.io/steel0237-sprintf/test/nginx:${TAG:-latest}
    ports:
      - "10081:80"
    logging:
      options:
        max-size: "50m"
        max-file: "5"
    environment:
      ENV: ${ENV:-pro}
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname == worker1]

