version: '3.8'

services:

  php:
    environment:
      XDEBUG_CONFIG: "remote_host=host.docker.internal remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    ports:
      - "81:80"
    logging:
      options:
        max-size: "50m"
        max-file: "5"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ../:/var/www/sanatoriy/data/www/putevka.com
      - ~/.ssh:/home/www-data/.ssh:ro

  nginx:
    ports:
      - "80:80"
    logging:
      options:
        max-size: "50m"
        max-file: "5"
    volumes:
      - ../:/var/www/sanatoriy/data/www/putevka.com

  postgresql:
    image: postgres:14.11-alpine3.19
    environment:
      TZ: "Europe/Moscow"
      POSTGRES_PASSWORD: ${DB_PASS:-putevka}
      POSTGRES_USER: ${DB_USER:-putevka}
      POSTGRES_DB: ${DB_NAME:-putevka}
    command: "-c log_statement=all"
    ports:
      - "5432:5432"
    logging:
      options:
        max-size: "50m"
        max-file: "5"

volumes:
  postgres_data:

