name: build and deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: steel0237-sprintf/template/.github/workflows/deploy.yml@main
    with:
      env: 'stage'
    secrets:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SSH_USER: ${{ secrets.SSH_USER }}



