name: build and deployment

#on:
#  push:
#    branches:
#      - main
on:
  push:
    branches:
      - test
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: stage
        type: choice
        options:
          - djserver
          - femil
          - stage
          - prod

jobs:
  build:
    permissions:
      contents: read
      packages: write
    uses: steel0237-sprintf/template/.github/workflows/php-build.yml@main
    with:
      env: ${{ inputs.environment || 'stage' }}

  deploy:
    permissions:
      contents: read
      packages: write
    uses: steel0237-sprintf/template/.github/workflows/deploy.yml@main
    needs: build
    with:
      env: ${{ inputs.environment || 'stage' }}

  deploy-prod:
    permissions:
      contents: read
      packages: write
    needs: [ build, deploy ]
    uses: steel0237-sprintf/template/.github/workflows/deploy.yml@main
    with:
      env: prod


#    runs-on: ubuntu-latest
#    environment: ${{ inputs.stage }}
#    steps:
#      - uses: actions/checkout@v4
#      - name: view the secrets context
#        shell: bash
#        run: |
#             echo "$SECRETS_CONTEXT"
#             echo "$SECRETS_CONTEXT" | jq -r 'keys[] as $k | "\($k)=\(.[$k])"'
#        env:
#         SECRETS_CONTEXT: ${{ vars.secret }}

#      - name: view the secrets context2
#        shell: bash
#        run: echo "$SECRETS_CONTEXT"
#        env:
#         SECRETS_CONTEXT: ${{ toJson(vars.test_$stage) }}

#  build:#    permissions:
#      contents: read
#      packages: write
#    uses: steel0237-sprintf/template/.github/workflows/php-build.yml@main
#    with:
#      env: 'pro'
#  deploy:
#    permissions:
#      contents: read
#      packages: write
#    uses: steel0237-sprintf/template/.github/workflows/deploy.yml@main
#    with:
#      env: 'stage'
#    secrets:
#      SSH_HOST: ${{ secrets.SSH_HOST }}
#      SSH_KEY: ${{ secrets.SSH_KEY }}
#      SSH_USER: ${{ secrets.SSH_USER }}











