name: build and deployment

#on:
#  push:
#    branches:
#      - main
on:
  push:
    branches:
      - test
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'stage'
        type: choice
        options:
          - djserver
          - femil
          - stage

jobs:
  set_environment:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    steps:
      - name: get config
        id: getconfig
        env:
         CONFIG_JSON: ${{ vars.CONFIG_JSON }}
        run: |
          echo "CONFIG_JSON=${CONFIG_JSON}" >> $GITHUB_OUTPUT

  build:
    permissions:
      contents: read
      packages: write
    needs: [set_environment]
    uses: steel0237-sprintf/template/.github/workflows/php-build.yml@main
    with:
      env: ${{ inputs.environment }}
      config: ${{ needs.set_environment.steps.getconfig.outputs.CONFIG_JSON }}


#  build:
#    runs-on: ubuntu-latest
#    environment: ${{ inputs.stage }}
#    steps:
#      - uses: actions/checkout@v4
#      - name: view the secrets context
#        shell: bash
#        run: |
#             echo "$SECRETS_CONTEXT"
#             echo "$SECRETS_CONTEXT" | jq -r 'keys[] as $k | "\($k)=\(.[$k])"'
#        env:
#         SECRETS_CONTEXT: ${{ vars.secret }}

#      - name: view the secrets context2
#        shell: bash
#        run: echo "$SECRETS_CONTEXT"
#        env:
#         SECRETS_CONTEXT: ${{ toJson(vars.test_$stage) }}

#  build:#    permissions:
#      contents: read
#      packages: write
#    uses: steel0237-sprintf/template/.github/workflows/php-build.yml@main
#    with:
#      env: 'pro'
#  deploy:
#    permissions:
#      contents: read
#      packages: write
#    uses: steel0237-sprintf/template/.github/workflows/deploy.yml@main
#    with:
#      env: 'stage'
#    secrets:
#      SSH_HOST: ${{ secrets.SSH_HOST }}
#      SSH_KEY: ${{ secrets.SSH_KEY }}
#      SSH_USER: ${{ secrets.SSH_USER }}











