name: build and deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: "Deploy to staging"
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - shell: bash
        env:
          SUPER_SECRET: ${{ secrets.SSH_KEY }}
        run: |
             echo "$SUPER_SECRET"
